### PR TITLE
Support for gpu batches + extra features

### PR DESCRIPTION
**Pull request by harisreedhar**
- Support image batches (gpu) for swapping (analysing, postprocessing etc still not batched yet)
- Add laplacian blending
- Add Face scale slider
- Add Face mask crop

### CODE REVIEW

**Comment by mukeshsnp12** [comment]
Thanks, can you give a little knowledge what these 3 options do and how to use them?

**Comment by harisreedhar** [comment]
@mukeshsnp12 
- ``Laplacian blending`` allows to blend source face with target image seamlessly (Effect is subtle but very noticeable in certain scenarios)
- ``Face scale`` - as name suggests it adjust scale of source image on target image.
- ``Crop mask`` - crops source face from different directions(``Top,Bottom,Left,Right``). ``Top`` cropping is especially helpful for hiding hairlines from source image. (cropping resolution without face enhancer is 128 and 512 with enhancement)

All these settings are available on other settings tab.

**Comment by mukeshsnp12** [comment]
Can you give choice option of post processing? Because I notice that even face swapping is good enough in most cases and many times we need not post processing and it can save a lot of time. Please give option to choose post processing or not. and save swapped images in result folder (for videos also), currently it is saving if we choose directory/images option only.

**Comment by mukeshsnp12** [comment]
When we cancel operation, it doesn't stop in most cases. we need to close app and run again to stop it.

**Comment by mukeshsnp12** [comment]
Btw, for single image face swapping, this app is the best. I tried almost all and Swap Mukham result is 95% accurate (I tried solo videos till now).

**Comment by harisreedhar** [comment]
@mukeshsnp12 
Posprocessing is necessary it can't be avoided. This is the step where swapped face is pasted back on original image. b/w in outputsettings you can enable ``keep sequence`` checkbox to keep image sequence

**Pull request merged**
